### ISSUE TITLE
[UPDATE]skin.sio2 4.0.5

### ISSUE THREAD

**Issue by fastcolors** [xbmc/repo-skins#122]
- Add-on name: sio2
  - Add-on ID: skin.sio2
  - Version number: 4.0.5
  - Kodi/repository version: Krypton
  - URL: https://github.com/fastcolors/skin.sio2
  - Revision/tag: 3ab3fe3  
  - Branch: master

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
hey @fastcolors could you please have a look at these issues:

1) two xml files fail validation
- DialogPVRChannelManager.xml:
missing closing bracket at line 169: ```<align>left</align```
- Includes_Variables.xml: 
use ```&amp;``` instead of ```&``` at line 86

2) several images are marked as executable, please fix that.
- full list: http://paste.ubuntu.com/26058569/

3) resource.uisounds.sio2 is listed as a dependency, but it is not available in our repo

4) undefined includes:
- DialogFavourites.xml: <include>Sets</include>
- MyMusicPlaylistEditor.xml: <include>HeadingL</include>
- MyPVRSearch.xml: <include>statusbiglist</include>
- MyPVRSearch.xml: <include>statusbiglist</include>
- MyVideoNav.xml: <include>moviebanners</include>
- MyVideoPlaylist.xml: <include>LargeListSlider</include>
- script-globalsearch-main.xml: <include>WindowOpenClose</include>

**Comment by fastcolors** [comment]
all should be fixed and merged into master branch :-)

**Comment by ronie** [comment]
added to the krypton repo, thx!
https://github.com/xbmc/repo-skins/commit/5734617d1e4a1b3ac0e0664c36251de3c2aeed19

**Comment by MartijnKaijser** [comment]
@fastcolors you define 8 screenshots in addon.xml and you only have 4 in resources. This causes a failure in our repo script

**Comment by fastcolors** [comment]
Sorry!! Will fix ASAP!!!!!!!! 😓

**Comment by fastcolors** [comment]
#131
