### ISSUE TITLE
[skin.metropolicon-krypton] 4.2.9

### ISSUE THREAD

**Issue by metropolicon** [xbmc/repo-skins#24]
### Add-on details:

- **General**
  - Add-on name: MetropolIcon
  - Add-on ID: skin.metropolicon-krypton
  - Version number: 4.2.9
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/metropolicon/skin.metropolicon.krypton
  - Revision/tag: 4.2.9
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by metropolicon** [comment]
please delete....sorry

**Comment by ronie** [comment]
thanx for submitting your skin to the addon repo.

as you're hopefully aware, we rarely accept skin mods in the repo.
that is, unless they are really really different from the original skin.
(in which case, you'd like to pick a name that doesn't resemble the original too much to avoid confusion)

nonetheless, i took metropolicons for a test spin and sadly bumped into quite a few issues.
i'll give a few examples...

**missing text on the homescreen menu**
![home](https://cloud.githubusercontent.com/assets/687265/22386612/30417f14-e4d8-11e6-9817-c7a11f70d69f.jpg)

**one of the views in pictures**
![pictures](https://cloud.githubusercontent.com/assets/687265/22386638/54ab4010-e4d8-11e6-97db-8560bb71b59f.jpg)

**video library, missing fanart and animations that do not work correctly**
![movies](https://cloud.githubusercontent.com/assets/687265/22386670/767329ba-e4d8-11e6-96eb-e825627edc4d.jpg)

**this looks like an 720p xml file copied to a 1080 folder without making any changes**
![settings](https://cloud.githubusercontent.com/assets/687265/22386706/a4621f5c-e4d8-11e6-9f14-98a3afd84b2b.jpg)

other issues i noticed due to copying 720p xml files without making proper adjustments:
- fonts are generally too small
- dialogs are not centered

some tips:
- use some xml validating tool. many xml files fail to validate.
- use case sensitive coding, i have the feeling i'm missing textures in several places due to this
- include license files for all fonts you use (they all need to by open-source / free to redistribute fonts)

recommended reading:
http://kodi.wiki/index.php?title=Add-on_rules



feel free to resubmit the skin in the future when you're confident it's well tested and most of the initial bugs have been ironed out.
