### ISSUE TITLE
skin.tetradui

### ISSUE THREAD

**Issue by gade01** [xbmc/repo-skins#372]
### Add-on details:
This is the initial release of skin.tetradui for Matrix repo.
https://forum.kodi.tv/showthread.php?tid=368683
@Ch3dd4rGoblin

Please make both [Ch3dd4rGoblin](https://forum.kodi.tv/member.php?action=profile&uid=465378) and [Gade](https://forum.kodi.tv/member.php?action=profile&uid=152411) admins of the skin.tetradui forum once created, thanks.
- **General**
  - Add-on name: TetradUI
  - Add-on ID: skin.tetradui
  - Version number: 1.3.5
  - Kodi/repository version: Matrix
- **Code location**
  - URL: https://github.com/gade01/skin.tetradui
  - Revision/tag: latest
  - Branch: master

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
it's been a while since a new skin was submitted to the addon repo, nice :-)

here's a few things that need some attention:

please rename **i**ncludesVariables.xml  to  **I**ncludesVariables.xml

Label not defined: 31936
xml/DialogPVRInfo.xml: line 151

Label not defined: 161
xml/DialogMusicInfo.xml: line 358

Label not defined: 31028
xml/LoginScreen.xml: line 63

invalid tag for control type=radiobutton: enabled
xml/SkinSettings.xml: line 277

invalid tag for control type=radiobutton: enabled
xml/SkinSettings.xml: line 284

invalid tag for control type=radiobutton: enabled
xml/SkinSettings.xml: line 291

invalid tag for control type=radiobutton: enabled
xml/SkinSettings.xml: line 298

invalid tag for control type=radiobutton: enabled
xml/SkinSettings.xml: line 305

(should be enable instead of enabled)

**Comment by gade01** [comment]
@ronie 
Thanks for the fast reply.

Nice catches. ;)
Yesterday I couldn't figure out what was wrong with the radiobutton enable/enabled issue reported by my skinning tool LOL.

Everything is fixed in the latest commit.

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-skins/commit/4c40a89f9bcaf13b8f6d52c7e2109a694f37ea27
